CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Trackball
CONFIG_ZMK_POINTING=y
CONFIG_I2C=y
CONFIG_ZMK_TRACKBALL_PIM447=y
CONFIG_INPUT=y
# Logging
CONFIG_ZMK_USB_LOGGING=y
CONFIG_LOG=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=5000
CONFIG_LOG_BUFFER_SIZE=16384
