manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: pim447
      url-base: https://github.com/t0bybr
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: pim447
      remote: pim447
      revision: main
      # revision: master
      # url: https://github.com/mwandzik/zmk-driver-pim447
      # path: modules/pim447
  self:
    path: config
